import type { Metadata } from "next";
import { Bitter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Personal Next.js Portfolio",
  description: "Generated by create next app",
};

const bitter = Bitter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bitter.className}>{children}</body>
    </html>
  );
}
