import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
{/** */ }
export const metadata: Metadata = {
  title: "Theodore Ng",
  description: "Generated by create next app",
};

const albert = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={albert.className}>{children}</body>
    </html>
  );
}
